### ISSUE TITLE
errors with file not found

### ISSUE THREAD

**Issue by chatango-kotarou** [necrodraco/AutoCompiler#1]
18-12-2017 20:46:59 start
18-12-2017 20:46:59 finished setting Ressources
18-12-2017 20:46:59 Missing Unpacked Files. Start Preparation Module
Can't exec "java": No such file or directory at src/Library.pm line 25.
Use of uninitialized value in concatenation (.) or string at src/PrepareManager.pm line 15.
Can't exec "java": No such file or directory at src/Library.pm line 25.
18-12-2017 20:46:59 Start Pulling newest Updates
18-12-2017 20:46:59 Pulling newest Updates finished
18-12-2017 20:46:59 Updates where found
18-12-2017 20:46:59 Images will be prepared to create Image File
: No such file or directoryro/pics/
 at src/Finder.pm line 72.
18-12-2017 20:46:59 Image Preparing finished
18-12-2017 20:46:59 Start creating of Image Archive File
IO error: Can't open  for write : No such file or directory
 at /usr/share/perl5/Archive/Zip/Archive.pm line 382.
        Archive::Zip::Archive::writeToFileNamed(Archive::Zip::Archive=HASH(0x3c97d68), undef) called at src/ImageWorker.pm line 71
        ImageWorker::archiveImages(ImageWorker=HASH(0x3e29010), undef, HASH(0x3e28fc8)) called at src/ImageWorker.pm line 84
        ImageWorker::archiving(ImageWorker=HASH(0x3e29010)) called at AutoCompiler.pl line 111
Error during writing to Archive  at src/ImageWorker.pm line 71

im not a perl dev so i cant debug this inside the project I have source files from github and scripts and pics in a folder called ygopro

**Comment by necrodraco** [comment]
Hey, 
sorry that I doesn't saw this issue earlier. 

It seems you doesn't have Java(Runtime Environment) installed. You can install it from https://www.java.com or from your package management. 

You can test if all needed modules are installed by running "perl tester.t". When you miss other modules you should get an command to install the missing modules. 

Which OS did you use? Because the System is only checked for linux systems. on Windows could be other bugs happen. 

ps: be inform that I changed the properties-files with yaml-files in the newer versions. These are configuration files where you can specifiy where all of your folders are.
